package com.mlbb.assistant.domain.usecase

import com.mlbb.assistant.domain.engine.DraftSession
import com.mlbb.assistant.domain.model.DraftHistoryItem
import com.mlbb.assistant.domain.repository.DraftSessionRepository
import javax.inject.Inject

/**
 * Persists a completed [DraftSession] as a [DraftHistoryItem].
 *
 * Called from [com.mlbb.assistant.presentation.draft.DraftViewModel] when the draft
 * phase transitions to [com.mlbb.assistant.domain.engine.DraftPhase.COMPLETE].
 *
 * Score computation uses simple heuristics from available session data so that
 * this use case stays pure (no android.* imports, no Room references).
 *
 * Simulation drafts ([DraftSession.isSimulation] == true) are still saved so
 * that the history screen can show them with a "Simulation" badge, but they are
 * excluded from [WeightCalibrator] calibration runs.
 *
 * @return the Room row-id of the saved record, or -1 on any failure.
 */
class SaveDraftSessionUseCase @Inject constructor(
    private val repository: DraftSessionRepository
) {
    suspend operator fun invoke(session: DraftSession): Long {
        val ourPicks   = session.ourPickedHeroes
        val enemyPicks = session.enemyPickedHeroes

        // Meta score: average win rate of our picks (0–100).
        val metaScore = if (ourPicks.isEmpty()) 50
                        else (ourPicks.map { it.winRate }.average() * 100).toInt()
                                .coerceIn(0, 100)

        // Counter score: ratio of our heroes that counter at least one enemy pick.
        val counterScore = if (ourPicks.isEmpty() || enemyPicks.isEmpty()) 50 else {
            val enemyIds  = enemyPicks.map { it.id }.toSet()
            val effective = ourPicks.count { hero -> hero.counters.any { it in enemyIds } }
            ((effective.toFloat() / ourPicks.size) * 100).toInt().coerceIn(0, 100)
        }

        // Synergy score: ratio of our picks that synergise with at least one ally.
        val synergyScore = if (ourPicks.size < 2) 50 else {
            val allyIds   = ourPicks.map { it.id }.toSet()
            val effective = ourPicks.count { hero -> hero.synergies.any { it in allyIds } }
            ((effective.toFloat() / ourPicks.size) * 100).toInt().coerceIn(0, 100)
        }

        // Overall draft score: weighted average (meta 40 %, counter 30 %, synergy 30 %).
        val draftScore = ((metaScore * 0.4 + counterScore * 0.3 + synergyScore * 0.3)).toInt()

        // Slot values of -1 represent unfilled/unavailable ban or pick slots, matching
        // the historical Room entity encoding (see DraftSessionEntity.enemyBanIds).
        val item = DraftHistoryItem(
            id                      = 0,   // auto-generated by Room
            timestamp               = System.currentTimeMillis(),
            rank                    = session.rank.display,
            draftScore              = draftScore,
            metaScore               = metaScore,
            counterScore            = counterScore,
            synergyScore            = synergyScore,
            followedRecommendations = session.followedRecommendations,
            totalRecommendations    = session.totalRecommendations,
            outcome                 = session.outcome,
            isSimulation            = session.isSimulation,
            yourPickIds             = ourPicks.map { it.id },
            ourTeamFirst            = session.ourTeamFirst,
            enemyBanIds             = (session.enemyBansR1 + session.enemyBansR2).map { it?.id ?: -1 },
            yourBanIds              = (session.ourBansR1 + session.ourBansR2).map { it?.id ?: -1 },
            enemyPickIds            = enemyPicks.map { it.id }
        )

        return runCatching { repository.saveSession(item) }.getOrDefault(-1L)
    }
}
